version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: prismaFirstProject
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - meu-volume-mysql:/var/lib/mysql
    restart: always

volumes:
  meu-volume-mysql: